### ISSUE TITLE
CRM 支持设置自定义 composer 镜像源吗？

### ISSUE THREAD

**Issue by MinsonLee** [slince/composer-registry-manager#24]
由于工作需要，需要使用公司自建的 composer 镜像源，但非工作时间段又需要切换回其他公共的源。请问是否有计划支持设置私有源地址，并进行管理呢？

**Comment by MinsonLee** [comment]
命令 `composer repo:add <repository-name> <repository-url> [<repository-location>]` 可以轻松实现

**Comment by slince** [comment]
是的； 如果不想要可以删了，或者直接重置回默认
