### ISSUE TITLE
升级版本之后，原有添加的 registry 丢失

### ISSUE THREAD

**Issue by lifesign** [slince/composer-registry-manager#3]
RT

**Comment by slince** [comment]
crm默认存储在包下面的crm.json里，升级之后会覆盖掉，下一步计划配置文件迁移出去，0.o

ps:有啥好方案不 ？

**Comment by lifesign** [comment]
把配置文件放用户目录下? 类似 `.crm.config` 之类的

**Comment by slince** [comment]
- 新版本配置已经移入到home config dir下面：

windows在 `C:\Users\用户名下\AppData\Roaming\ComposerRegistryManager\crm.json``

linux在` ~/.config/composer-registry-manager/crm.json`

- 同时包名已经修改，按照下面命令更新

```bash
$ composer global remove   slince/crm
$ composer global require slince/composer-registry-manager
```

- 命令用法不变，`crm -l` 加入logo

**Comment by lifesign** [comment]
👍
