### ISSUE TITLE
ubuntu crm ls 指令报错 Can not find current registry, error: Syntax error ，项目目录下面的composer.json并没有配镜像地址

### ISSUE THREAD

**Issue by nixizhiguang** [slince/composer-registry-manager#4]
[Slince\Crm\Exception\RuntimeException]             
  Can not find current registry, error: Syntax error ，就看到这个错，新手，没看过composer源码，有什么可以提交的错误日志吗？

**Comment by slince** [comment]
可能你的composer版本有点低，升级下看看
```
 composer self-update 
```
