### ISSUE TITLE
建议默认删掉laravel-china和phpcomposer源

### ISSUE THREAD

**Issue by chisaato** [slince/composer-registry-manager#9]
参见 
[Laravel China 镜像完成历史使命，将于两个月后停用
](https://learnku.com/articles/30758)  
而phpcomposer早就暂停了更新

**Comment by slince** [comment]
tks! 可以的话望直接提个pr 😄

**Comment by slince** [comment]
感谢 @sy-records  的贡献，现在已经移除了
